"""initial

Revision ID: d34030ed69f9
Revises: 
Create Date: 2026-08-24 23:14:35.544599+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd34030ed69f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('duracion', sa.Enum('anual', 'cuatrimestral', name='duracionenum'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materias_codigo'), 'materias', ['codigo'], unique=True)
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('periodos_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('anual', 'primer_cuatrimestre', 'segundo_cuatrimestre', name='tipoperiodoenum'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_periodos_academicos_id'), 'periodos_academicos', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('administrador', 'profesor_directivo', 'alumno', name='rolenum'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_academicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comisiones_id'), 'comisiones', ['id'], unique=False)
    op.create_table('registro_cambios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabla_afectada', sa.String(length=100), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('valor_anterior', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('valor_nuevo', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_cambios_fecha'), 'registro_cambios', ['fecha'], unique=False)
    op.create_index(op.f('ix_registro_cambios_id'), 'registro_cambios', ['id'], unique=False)
    op.create_index(op.f('ix_registro_cambios_registro_id'), 'registro_cambios', ['registro_id'], unique=False)
    op.create_index(op.f('ix_registro_cambios_tabla_afectada'), 'registro_cambios', ['tabla_afectada'], unique=False)
    op.create_index(op.f('ix_registro_cambios_usuario_id'), 'registro_cambios', ['usuario_id'], unique=False)
    op.create_table('cursadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('comision_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('aula', sa.String(length=50), nullable=True),
    sa.Column('horario', sa.String(length=200), nullable=True),
    sa.Column('modalidad', sa.Enum('presencial', 'virtual', 'hibrida', name='modalidadenum'), nullable=False),
    sa.Column('info_adicional', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comision_id'], ['comisiones.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos_academicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursadas_comision_id'), 'cursadas', ['comision_id'], unique=False)
    op.create_index(op.f('ix_cursadas_id'), 'cursadas', ['id'], unique=False)
    op.create_index(op.f('ix_cursadas_materia_id'), 'cursadas', ['materia_id'], unique=False)
    op.create_index(op.f('ix_cursadas_periodo_id'), 'cursadas', ['periodo_id'], unique=False)
    op.create_table('usuario_comision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comision_id', sa.Integer(), nullable=False),
    sa.Column('inscripto_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comision_id'], ['comisiones.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'comision_id', name='uq_usuario_comision')
    )
    op.create_index(op.f('ix_usuario_comision_comision_id'), 'usuario_comision', ['comision_id'], unique=False)
    op.create_index(op.f('ix_usuario_comision_id'), 'usuario_comision', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_comision_usuario_id'), 'usuario_comision', ['usuario_id'], unique=False)
    op.create_table('cursada_excepciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cursada_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('reubicacion', 'suspension', name='tipoexcepcionenum'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('aula_nueva', sa.String(length=50), nullable=True),
    sa.Column('horario_nuevo', sa.String(length=200), nullable=True),
    sa.Column('cargado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cursada_id'], ['cursadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursada_excepciones_cursada_id'), 'cursada_excepciones', ['cursada_id'], unique=False)
    op.create_index(op.f('ix_cursada_excepciones_id'), 'cursada_excepciones', ['id'], unique=False)
    op.create_table('cursada_profesor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cursada_id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cursada_id'], ['cursadas.id'], ),
    sa.ForeignKeyConstraint(['profesor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cursada_id', 'profesor_id', name='uq_cursada_profesor')
    )
    op.create_index(op.f('ix_cursada_profesor_cursada_id'), 'cursada_profesor', ['cursada_id'], unique=False)
    op.create_index(op.f('ix_cursada_profesor_id'), 'cursada_profesor', ['id'], unique=False)
    op.create_index(op.f('ix_cursada_profesor_profesor_id'), 'cursada_profesor', ['profesor_id'], unique=False)
    op.create_table('eventos_calendario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('paro', 'asueto', 'evento_cultural', 'fecha_examen', 'otro', name='tipoeventoenum'), nullable=False),
    sa.Column('origen', sa.String(length=100), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fin', sa.Time(), nullable=True),
    sa.Column('alcance', sa.Enum('general', 'comision', 'materia_especifica', name='alcanceeventoenum'), nullable=False),
    sa.Column('comision_id', sa.Integer(), nullable=True),
    sa.Column('cursada_id', sa.Integer(), nullable=True),
    sa.Column('cargado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['comision_id'], ['comisiones.id'], ),
    sa.ForeignKeyConstraint(['cursada_id'], ['cursadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_calendario_alcance'), 'eventos_calendario', ['alcance'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_comision_id'), 'eventos_calendario', ['comision_id'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_cursada_id'), 'eventos_calendario', ['cursada_id'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_fecha_inicio'), 'eventos_calendario', ['fecha_inicio'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_id'), 'eventos_calendario', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_calendario_tipo'), 'eventos_calendario', ['tipo'], unique=False)
    op.create_table('materiales_apoyo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cursada_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('apunte', 'video', 'ejercicio', 'bibliografía', 'otro', name='tipomaterialenum'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cargado_por', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cargado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['cursada_id'], ['cursadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiales_apoyo_cursada_id'), 'materiales_apoyo', ['cursada_id'], unique=False)
    op.create_index(op.f('ix_materiales_apoyo_id'), 'materiales_apoyo', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materiales_apoyo_id'), table_name='materiales_apoyo')
    op.drop_index(op.f('ix_materiales_apoyo_cursada_id'), table_name='materiales_apoyo')
    op.drop_table('materiales_apoyo')
    op.drop_index(op.f('ix_eventos_calendario_tipo'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_id'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_fecha_inicio'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_cursada_id'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_comision_id'), table_name='eventos_calendario')
    op.drop_index(op.f('ix_eventos_calendario_alcance'), table_name='eventos_calendario')
    op.drop_table('eventos_calendario')
    op.drop_index(op.f('ix_cursada_profesor_profesor_id'), table_name='cursada_profesor')
    op.drop_index(op.f('ix_cursada_profesor_id'), table_name='cursada_profesor')
    op.drop_index(op.f('ix_cursada_profesor_cursada_id'), table_name='cursada_profesor')
    op.drop_table('cursada_profesor')
    op.drop_index(op.f('ix_cursada_excepciones_id'), table_name='cursada_excepciones')
    op.drop_index(op.f('ix_cursada_excepciones_cursada_id'), table_name='cursada_excepciones')
    op.drop_table('cursada_excepciones')
    op.drop_index(op.f('ix_usuario_comision_usuario_id'), table_name='usuario_comision')
    op.drop_index(op.f('ix_usuario_comision_id'), table_name='usuario_comision')
    op.drop_index(op.f('ix_usuario_comision_comision_id'), table_name='usuario_comision')
    op.drop_table('usuario_comision')
    op.drop_index(op.f('ix_cursadas_periodo_id'), table_name='cursadas')
    op.drop_index(op.f('ix_cursadas_materia_id'), table_name='cursadas')
    op.drop_index(op.f('ix_cursadas_id'), table_name='cursadas')
    op.drop_index(op.f('ix_cursadas_comision_id'), table_name='cursadas')
    op.drop_table('cursadas')
    op.drop_index(op.f('ix_registro_cambios_usuario_id'), table_name='registro_cambios')
    op.drop_index(op.f('ix_registro_cambios_tabla_afectada'), table_name='registro_cambios')
    op.drop_index(op.f('ix_registro_cambios_registro_id'), table_name='registro_cambios')
    op.drop_index(op.f('ix_registro_cambios_id'), table_name='registro_cambios')
    op.drop_index(op.f('ix_registro_cambios_fecha'), table_name='registro_cambios')
    op.drop_table('registro_cambios')
    op.drop_index(op.f('ix_comisiones_id'), table_name='comisiones')
    op.drop_table('comisiones')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_periodos_academicos_id'), table_name='periodos_academicos')
    op.drop_table('periodos_academicos')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_index(op.f('ix_materias_codigo'), table_name='materias')
    op.drop_table('materias')
    # ### end Alembic commands ###
